version: '3.9'

services:
  # MongoDB service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27018:27017
    volumes:
      - mongo_db:/data/db
  # Node API service
  api:
    image: node:latest
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 3000
      DB_NAME: strime
      MONGODB_URI: mongodb://mongo_db:27017
      NAME: TrulyMittal
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}